/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CertificationsRouteImport } from './routes/certifications'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as HackathonsIndexRouteImport } from './routes/hackathons.index'
import { Route as HackathonsIdRouteImport } from './routes/hackathons.$id'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsHandGestureControlRouteImport } from './routes/projects.hand-gesture-control'
import { Route as ProjectsKeralaTourismRouteImport } from './routes/projects.kerala-tourism'
import { Route as ProjectsSafetyHelmetRouteImport } from './routes/projects.safety-helmet'
import { Route as ProjectsSpotifyCloneRouteImport } from './routes/projects.spotify-clone'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationsRoute = CertificationsRouteImport.update({
  id: '/certifications',
  path: '/certifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsIndexRoute = HackathonsIndexRouteImport.update({
  id: '/hackathons/',
  path: '/hackathons/',
  getParentRoute: () => rootRouteImport,
} as any)
const HackathonsIdRoute = HackathonsIdRouteImport.update({
  id: '/hackathons/$id',
  path: '/hackathons/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsHandGestureControlRoute =
  ProjectsHandGestureControlRouteImport.update({
    id: '/projects/hand-gesture-control',
    path: '/projects/hand-gesture-control',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsKeralaTourismRoute = ProjectsKeralaTourismRouteImport.update({
  id: '/projects/kerala-tourism',
  path: '/projects/kerala-tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSafetyHelmetRoute = ProjectsSafetyHelmetRouteImport.update({
  id: '/projects/safety-helmet',
  path: '/projects/safety-helmet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSpotifyCloneRoute = ProjectsSpotifyCloneRouteImport.update({
  id: '/projects/spotify-clone',
  path: '/projects/spotify-clone',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/hackathons/$id': typeof HackathonsIdRoute
  '/projects/hand-gesture-control': typeof ProjectsHandGestureControlRoute
  '/projects/kerala-tourism': typeof ProjectsKeralaTourismRoute
  '/projects/safety-helmet': typeof ProjectsSafetyHelmetRoute
  '/projects/spotify-clone': typeof ProjectsSpotifyCloneRoute
  '/hackathons/': typeof HackathonsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/hackathons/$id': typeof HackathonsIdRoute
  '/projects/hand-gesture-control': typeof ProjectsHandGestureControlRoute
  '/projects/kerala-tourism': typeof ProjectsKeralaTourismRoute
  '/projects/safety-helmet': typeof ProjectsSafetyHelmetRoute
  '/projects/spotify-clone': typeof ProjectsSpotifyCloneRoute
  '/hackathons': typeof HackathonsIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certifications': typeof CertificationsRoute
  '/contact': typeof ContactRoute
  '/resume': typeof ResumeRoute
  '/skills': typeof SkillsRoute
  '/hackathons/$id': typeof HackathonsIdRoute
  '/projects/hand-gesture-control': typeof ProjectsHandGestureControlRoute
  '/projects/kerala-tourism': typeof ProjectsKeralaTourismRoute
  '/projects/safety-helmet': typeof ProjectsSafetyHelmetRoute
  '/projects/spotify-clone': typeof ProjectsSpotifyCloneRoute
  '/hackathons/': typeof HackathonsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/certifications'
    | '/contact'
    | '/resume'
    | '/skills'
    | '/hackathons/$id'
    | '/projects/hand-gesture-control'
    | '/projects/kerala-tourism'
    | '/projects/safety-helmet'
    | '/projects/spotify-clone'
    | '/hackathons/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/certifications'
    | '/contact'
    | '/resume'
    | '/skills'
    | '/hackathons/$id'
    | '/projects/hand-gesture-control'
    | '/projects/kerala-tourism'
    | '/projects/safety-helmet'
    | '/projects/spotify-clone'
    | '/hackathons'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/certifications'
    | '/contact'
    | '/resume'
    | '/skills'
    | '/hackathons/$id'
    | '/projects/hand-gesture-control'
    | '/projects/kerala-tourism'
    | '/projects/safety-helmet'
    | '/projects/spotify-clone'
    | '/hackathons/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CertificationsRoute: typeof CertificationsRoute
  ContactRoute: typeof ContactRoute
  ResumeRoute: typeof ResumeRoute
  SkillsRoute: typeof SkillsRoute
  HackathonsIdRoute: typeof HackathonsIdRoute
  ProjectsHandGestureControlRoute: typeof ProjectsHandGestureControlRoute
  ProjectsKeralaTourismRoute: typeof ProjectsKeralaTourismRoute
  ProjectsSafetyHelmetRoute: typeof ProjectsSafetyHelmetRoute
  ProjectsSpotifyCloneRoute: typeof ProjectsSpotifyCloneRoute
  HackathonsIndexRoute: typeof HackathonsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifications': {
      id: '/certifications'
      path: '/certifications'
      fullPath: '/certifications'
      preLoaderRoute: typeof CertificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons/': {
      id: '/hackathons/'
      path: '/hackathons'
      fullPath: '/hackathons/'
      preLoaderRoute: typeof HackathonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hackathons/$id': {
      id: '/hackathons/$id'
      path: '/hackathons/$id'
      fullPath: '/hackathons/$id'
      preLoaderRoute: typeof HackathonsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/hand-gesture-control': {
      id: '/projects/hand-gesture-control'
      path: '/projects/hand-gesture-control'
      fullPath: '/projects/hand-gesture-control'
      preLoaderRoute: typeof ProjectsHandGestureControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/kerala-tourism': {
      id: '/projects/kerala-tourism'
      path: '/projects/kerala-tourism'
      fullPath: '/projects/kerala-tourism'
      preLoaderRoute: typeof ProjectsKeralaTourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/safety-helmet': {
      id: '/projects/safety-helmet'
      path: '/projects/safety-helmet'
      fullPath: '/projects/safety-helmet'
      preLoaderRoute: typeof ProjectsSafetyHelmetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/spotify-clone': {
      id: '/projects/spotify-clone'
      path: '/projects/spotify-clone'
      fullPath: '/projects/spotify-clone'
      preLoaderRoute: typeof ProjectsSpotifyCloneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CertificationsRoute: CertificationsRoute,
  ContactRoute: ContactRoute,
  ResumeRoute: ResumeRoute,
  SkillsRoute: SkillsRoute,
  HackathonsIdRoute: HackathonsIdRoute,
  ProjectsHandGestureControlRoute: ProjectsHandGestureControlRoute,
  ProjectsKeralaTourismRoute: ProjectsKeralaTourismRoute,
  ProjectsSafetyHelmetRoute: ProjectsSafetyHelmetRoute,
  ProjectsSpotifyCloneRoute: ProjectsSpotifyCloneRoute,
  HackathonsIndexRoute: HackathonsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
